Up

diff --git a/.github/workflows/Openwrt-AutoBuild.yml b/.github/workflows/Openwrt-AutoBuild.yml
--- a/.github/workflows/Openwrt-AutoBuild.yml
+++ b/.github/workflows/Openwrt-AutoBuild.yml
@@ -143,68 +143,68 @@ jobs:
         ln -sf /mnt/openwrt/build_dir openwrt/build_dir
         sudo ln -sf openwrt/staging_dir /mnt/openwrt/staging_dir
 
-    - name: Load openwrt .config
-      run: |
-        cd openwrt
-        wget -O .config https://downloads.openwrt.org/releases/25.12.2/targets/x86/64/config.buildinfo 
-        cat feeds.conf.default
+#    - name: Load openwrt .config
+#      run: |
+#        cd openwrt
+#        wget -O .config https://downloads.openwrt.org/releases/25.12.2/targets/x86/64/config.buildinfo 
+#        cat feeds.conf.default
 
 
      
 
-#    - name: Load custom configuration
-#      run: |
-#        function git_clone_path() {
-#          trap 'rm -rf "$tmpdir"' EXIT
-#          branch="$1" rurl="$2" mv="$3"
-#          [[ "$mv" != "mv" ]] && shift 2 || shift 3
-#          rootdir="$PWD"
-#          tmpdir="$(mktemp -d)" || exit 1
-#          if [ ${#branch} -lt 10 ]; then
-#          git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$rurl" "$tmpdir"
-#          cd "$tmpdir"
-#          else
-#          git clone --filter=blob:none --sparse "$rurl" "$tmpdir"
-#          cd "$tmpdir"
-#          git checkout $branch
-#          fi
-#          if [ "$?" != 0 ]; then
-#            echo "error on $rurl"
-#            exit 1
-#          fi
-#          git sparse-checkout init --cone
-#          git sparse-checkout set $@
-#          [[ "$mv" != "mv" ]] && cp -rn ./* $rootdir/ || mv -n $@/* $rootdir/$@/
-#          cd $rootdir
-#          }
-#        export -f git_clone_path
-#        cp -rf devices/common/. openwrt/
-#        cp -rf devices/${{matrix.target}}/. openwrt/
-#        cp -rf devices openwrt/
-#        cd openwrt
-#        chmod +x devices/common/$DIY_SH
-#        /bin/bash "devices/common/$DIY_SH"
-#        cp -f devices/common/$CONFIG_FILE .config
-#        if [ -f "devices/${{matrix.target}}/$CONFIG_FILE" ]; then
-#          echo >> .config
-#          cat devices/${{matrix.target}}/$CONFIG_FILE >> .config
-#        fi
-#        if [ -f "devices/${{matrix.target}}/$DIY_SH" ]; then
-#          chmod +x devices/${{matrix.target}}/$DIY_SH
-#          echo "/bin/bash devices/${{matrix.target}}/$DIY_SH"
-#          /bin/bash "devices/${{matrix.target}}/$DIY_SH"
-#        fi
-#        cp -Rf ./diy/* ./ || true
+    - name: Load custom configuration
+      run: |
+        function git_clone_path() {
+          trap 'rm -rf "$tmpdir"' EXIT
+          branch="$1" rurl="$2" mv="$3"
+          [[ "$mv" != "mv" ]] && shift 2 || shift 3
+          rootdir="$PWD"
+          tmpdir="$(mktemp -d)" || exit 1
+          if [ ${#branch} -lt 10 ]; then
+          git clone -b "$branch" --depth 1 --filter=blob:none --sparse "$rurl" "$tmpdir"
+          cd "$tmpdir"
+          else
+          git clone --filter=blob:none --sparse "$rurl" "$tmpdir"
+          cd "$tmpdir"
+          git checkout $branch
+          fi
+          if [ "$?" != 0 ]; then
+            echo "error on $rurl"
+            exit 1
+          fi
+          git sparse-checkout init --cone
+          git sparse-checkout set $@
+          [[ "$mv" != "mv" ]] && cp -rn ./* $rootdir/ || mv -n $@/* $rootdir/$@/
+          cd $rootdir
+        }
+        export -f git_clone_path
+        cp -rf devices/common/. openwrt/
+        cp -rf devices/${{matrix.target}}/. openwrt/
+        cp -rf devices openwrt/
+        cd openwrt
+        chmod +x devices/common/$DIY_SH
+        /bin/bash "devices/common/$DIY_SH"
+        cp -f devices/common/$CONFIG_FILE .config
+        if [ -f "devices/${{matrix.target}}/$CONFIG_FILE" ]; then
+          echo >> .config
+          cat devices/${{matrix.target}}/$CONFIG_FILE >> .config
+        fi
+        if [ -f "devices/${{matrix.target}}/$DIY_SH" ]; then
+          chmod +x devices/${{matrix.target}}/$DIY_SH
+          echo "/bin/bash devices/${{matrix.target}}/$DIY_SH"
+          /bin/bash "devices/${{matrix.target}}/$DIY_SH"
+        fi
+        cp -Rf ./diy/* ./ || true
 
-#    - name: Apply patches
-#      run: |
-#        cd openwrt
-#        cp -rn devices/common/patches devices/${{matrix.target}}/
-#          if [ -n "$(ls -A devices/${{matrix.target}}/*.bin.patch 2>/dev/null)" ]; then
-#            git apply devices/${{matrix.target}}/patches/*.bin.patch
-#          fi
-#          find "devices/${{matrix.target}}/patches" -maxdepth 1 -type f -name '*.revert.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "patch -d './' -R --no-backup-if-mismatch -p1 -F 1 --ignore-whitespace -i '%'"
-#          find "devices/${{matrix.target}}/patches" -maxdepth 1 -type f -name '*.patch' ! -name '*.revert.patch' ! -name '*.bin.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "patch -d './' --no-backup-if-mismatch -p1 -F 1 --ignore-whitespace -i '%'"
+    - name: Apply patches
+      run: |
+        cd openwrt
+        cp -rn devices/common/patches devices/${{matrix.target}}/
+          if [ -n "$(ls -A devices/${{matrix.target}}/*.bin.patch 2>/dev/null)" ]; then
+            git apply devices/${{matrix.target}}/patches/*.bin.patch
+          fi
+          find "devices/${{matrix.target}}/patches" -maxdepth 1 -type f -name '*.revert.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "patch -d './' -R --no-backup-if-mismatch -p1 -F 1 --ignore-whitespace -i '%'"
+          find "devices/${{matrix.target}}/patches" -maxdepth 1 -type f -name '*.patch' ! -name '*.revert.patch' ! -name '*.bin.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "patch -d './' --no-backup-if-mismatch -p1 -F 1 --ignore-whitespace -i '%'"
 
     - name: Defconfig
       run: |
@@ -227,15 +227,15 @@ jobs:
 
     - name: SSH connection to Actions
       uses: kiddin9/debugger-action@master
-#      if: contains(github.event.action, 'ssh')
+      if: contains(github.event.action, 'ssh')
 
-    - name: Build OpenWrt
-      working-directory: openwrt
-      run: |
-        ./scripts/feeds update -a
-        ./scripts/feeds install -a
-        # Явная сборка тулчейна перед ядром
-        make toolchain/install -j$(nproc)
+#    - name: Build OpenWrt
+#      working-directory: openwrt
+#      run: |
+#        ./scripts/feeds update -a
+#        ./scripts/feeds install -a
+#        # Явная сборка тулчейна перед ядром
+#        make toolchain/install -j$(nproc)
 
     - name: Compile the firmware
       id: compile
